setting:
  request: # 网络请求设置
    timeout: 10 # 请求超时时间
    ssl: false  # 是否进行ssl验证（适配http，但对相应请求会变慢）

  gitee_friends_links: # gitee友链配置
    enable: false # 使用时请设置为true
    type: normal # volantis用户请在这里填写 volantis
    owner: yourname # 填写你的gitee用户名
    repo: yourrepo # 填写你的gitee仓库名
    state: open # 填写抓取的issue状态(open/progressing/closed)

  block_word: # 屏蔽sitemap链接关键词
    - 'index'
    - 'json'
    - 'tags'
    - 'categories'
    - 'record'
    - 'sort'

  block_chars: # 屏蔽sitemap获取标题的分割字符
    - '|'
    - '::'
    - '-'
    - '・'
    - '绒布球'

  block_site: # 屏蔽站点
    - https://example.com/