name: update-friends-posts

on: 
  push:
    branches: 
     - master
  schedule:
    - cron: "0 0,6,12,18,21 * * *"
  watch:
    types: [started]

env:
  # 通用配置
  STORAGE_TYPE: leancloud # 如果不配置，默认为leancloud
  LINK: ${{ secrets.LINK }}
  PROXY: ${{ secrets.PROXY }}
  # leancloud配置
  APPID: ${{ secrets.APPID }}
  APPKEY: ${{ secrets.APPKEY }}
  # mysql配置
  MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  MYSQL_IP: ${{ secrets.MYSQL_IP }}
  MYSQL_DB: ${{ secrets.MYSQL_DB }}
  # sqlite配置
  GITHUB_NAME: ${{ secrets.GITHUB_NAME }}
  GITHUB_EMAIL: ${{ secrets.GITHUB_EMAIL }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install requirements
      working-directory: ./hexo_circle_of_friends
      run: |
        pip install -r requirement.txt

    - name: leancloud Update posts # leancloud
      if: ${{ env.STORAGE_TYPE == 'leancloud' }}
      env:
        APP_ID: ${{ secrets.APPID }}
        APP_KEY: ${{ secrets.APPKEY }}
        LINK: ${{ secrets.LINK }}
        PROXY: ${{ secrets.PROXY }}
      working-directory: ./hexo_circle_of_friends
      run: | 
        python run.py

    - name: mysql Update posts # mysql
      if: ${{ env.STORAGE_TYPE == 'mysql' }}
      env:
        MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_IP: ${{ secrets.MYSQL_IP }}
        MYSQL_DB: ${{ secrets.MYSQL_DB }}
      working-directory: ./hexo_circle_of_friends
      run: |
        python run.py

    - name: sqlite Update posts # sqlite
      if: ${{ env.STORAGE_TYPE == 'sqlite' }}
      env:
        SQLITE_DB: ${{ secrets.SQLITE_DB }}
      working-directory: ./hexo_circle_of_friends
      run: |
        python run.py

    - name: Push sqlite data # sqlite push
      if: ${{ env.STORAGE_TYPE == 'sqlite' }}
      uses: github-actions-x/commit@v2.8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update data"
        files: data.db
        rebase: 'true'
        name: ${{ env.GITHUB_NAME }}
        email: ${{ env.GITHUB_EMAIL }}